### ISSUE TITLE
ServiceRequestForm

### ISSUE THREAD

**Issue by eudyptula** [arrowhead-f/client-java#1]
Should any key be accepted in ServiceRequestForm::setOrchestrationFlags, or should it check whether each key is in the flagKeys list?

**Comment by eudyptula** [comment]
Also noticed that ServiceRequestForm::validateCrossParameterConstraints() is never called. In my refactored version I'm going to call it as part of the Builder::build() method.

**Comment by uzoltan** [comment]
validateCrossParameterConstraints: On the server side, it is called by the Orchestrator, when it receives a new SRF. The POJO was just copied over from the core-java repo. Self checking inside the build method is a fine idea, fail fast is better :)

I think it does not hurt if unknown orch flags are also in the hashmap, it doesn't effect processing. As long it's not spammed full with random stuff :) I can put a size constraint on the hashmap, I'll commit that change on the core repo.

**Comment by uzoltan** [comment]
Here is the commit for the size constraint: https://github.com/arrowhead-f/core-java/commit/b0e8e0ff58dbf101da7cfdb157ccb85640084a72

**Comment by eudyptula** [comment]
Ok, copied into my local version of https://github.com/eudyptula/arrowheadclient/tree/feature/refactored will be pushed into that later.
But, have no clue if that branch will eventually make the develop branch yet though...
