### ISSUE TITLE
HTTP 415 currently gets mapped to a HTTP 500 error code

### ISSUE THREAD

**Issue by eudyptula** [arrowhead-f/client-java#6]
If the server throws a NotSupportedException exception with the message "HTTP 415 Unsupported Media Type", the client currently gets the 500 status code back:

```
2019-02-18 09:17:11  INFO  {
  "errorMessage" : "class javax.ws.rs.NotSupportedException: HTTP 415 Unsupported Media Type",
  "errorCode" : 500,
  "exceptionType" : "GENERIC",
  "origin" : "https://192.38.56.154:9808/incoming",
  "documentation" : "https://github.com/hegeduscs/arrowhead/tree/4.0/documentation"
}
```

**Comment by uzoltan** [comment]
this would be the same for the core systems too. I will create a new exception mapper for them later this week when I have the time.

**Comment by uzoltan** [comment]
I pushed commits to both the repositories (core and client) which added a new exception mapper to handle this scenario.
